---
title: "Prac project"
author: "Nazmul Hossain"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
#read data
train <- read.csv(file = file.choose(), header = T, sep = ",")
```

```{r}
#read data
test <- read.csv(file = file.choose(), header = T, sep = ",")

```


```{r}
dim(train)
```

#load library
```{r}
library(tidyverse)
library(randomForest)
library(rpart)
library(modelr)
```

#stucture of data
```{r}
str(train)
```
#getting rid of IDs


```{r}
names(train)
dim(train)
```
#model
#train a decision tree based our data set

```{r}
fit <- rpart(SalePrice ~ LotFrontage + LotArea + Street + Utilities + HouseStyle + OverallQual + FullBath + HalfBath, data = train)
```

```{r}
#plot our tree
plot(fit, uniform = T)
# add text labels & make them 60% as big as they are by default
text(fit, cex= .7)
```



```{r}
print("Making predictions for the following 5 houses:")
print(head(train))

print("The predictions are")
print(predict(fit, head(train)))

print("Actual price")
print(head(train$SalePrice))
```


```{r}
#get the mean average error of our model
mae(model = fit, data = train)
```

```{r}
fit2 <- rpart(SalePrice~ LotFrontage + LotArea + Street + Utilities + HouseStyle + OverallQual + FullBath + HalfBath, data = all)
```

```{r}
# get the mean average error for our new model, based on our test data
mae(model = fit2, data = test)
```

